# Imagem base do Python
FROM python:3

# Copiar o script Python para dentro do container
COPY mascarar.py /app/mascarar.py

# Definir o diretório de trabalho
WORKDIR /app

# Executar o script Python ao iniciar o container
CMD ["python", "mascarar.py"]
